### ISSUE TITLE
How do you build the URL?

### ISSUE THREAD

**Issue by ledux6** [tastelessjolt/youtube-dl-android#19]
Hello,

I'm digging around your code and trying to fully comprehend how it all works. 

I'm particularly interested how do you build this URL:
`https://r2---sn-apuoxu-30ol.googlevideo.com/videoplayback?itag=140&source=youtube&signature=D57B903AA9628708FE65C3A7B6DEBBC11C1615DC.240F806BFD2258385BBFA1D77BC2C8D60C1FCB82&clen=19589536&fvip=3&txp=5535432&initcwndbps=2080000&expire=1548800675&ei=Q35QXOfpDNHF7gONqICoCQ&key=yt6&keepalive=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mm=31%2C29&ip=158.129.27.115&mn=sn-apuoxu-30ol%2Csn-4g5e6nez&ms=au%2Crdu&requiressl=yes&mt=1548778987&pl=18&mv=m&id=o-AFWCexAD0GwvgItXIVrkQzn2L6iuFPdftllpgyRR51ZP&dur=1210.386&mime=audio%2Fmp4&ipbits=0&gir=yes&c=WEB&lmt=1547401178781647&ratebypass=yes`
Because I'm mostly interested in the downloading aspect I can't seem to generate it.

**Comment by tastelessjolt** [comment]
Hey, since this is just a one to one copy of the original `youtube-dl` which I've linked it in the readme file. You may find the working there easier to understand than my code. If you're still facing problem understanding, then let me know, I'll update the readme with the working of the downloader.
