### ISSUE TITLE
Good App. However, some videos do not work.

### ISSUE THREAD

**Issue by chaocharleswang** [tastelessjolt/youtube-dl-android#4]
Please check the following video:

https://www.youtube.com/watch?v=5_yKSr8xf1U

Thanks!

**Comment by tastelessjolt** [comment]
## [Edit]
It is actually related to `player-age-gate-content`. This is not yet handled in the app. I have to go through `youtube-dl` to see how it is handled.  

------
I think the problem is related to the default quality it selects. This app currently automatically downloads 720p videos. 

I'll look into this video. Thanks for reporting.

**Comment by chaocharleswang** [comment]
Wait for your solutions 👍  Thanks!

**Comment by TooLazyy** [comment]
Same problem here. 
@tastelessjolt Python youtube-dl has updated recently.

**Comment by tastelessjolt** [comment]
I just tried it again, now it's working, so I'm closing this.
